import { Providers } from '@/components/shared/providers'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.scss'

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

const poppins = Poppins({
	variable: '--font-poppins',
	weight: ['400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${poppins.variable}`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
