import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import theme from '../theme'

import { ButtonGroupTheme } from '@/components/shared/button-group-theme'
import { Box } from '@mui/material'
import './globals.scss'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<Box
							sx={{
								position: 'relative',
								width: '100vw',
								minHeight: '100vh',
								bgcolor: 'background.default',
								color: 'text.primary',
							}}
						>
							<ButtonGroupTheme />
							{children}
						</Box>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	)
}
