import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import theme from '../theme'

import { Box } from '@mui/material'
import './globals.scss'

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.variable}`}>
				<AppRouterCacheProvider>
					<ThemeProvider theme={theme}>
						<Box
							sx={{
								position: 'relative',
								width: '100vw',
								minHeight: '100vh',
								bgcolor: 'background.default',
								color: 'text.primary',
							}}
						>
							{children}
						</Box>
					</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	)
}
