import { SidebarLeft, SidebarRight } from '@/components/shared'
import theme from '@/theme'
import { Box, ThemeProvider } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function DashboardLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<AppRouterCacheProvider>
			<ThemeProvider theme={theme}>
				<Box sx={{ display: 'flex', color: 'text.primary' }}>
					<SidebarLeft />
					{children}
					<SidebarRight />
				</Box>
			</ThemeProvider>
		</AppRouterCacheProvider>
	)
}
