import { DashboardPageLayout } from '@/components/shared/dashboard-page-layout'
import theme from '@/theme'
import { ThemeProvider } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Next-Network',
	description: 'Generated by create next app',
}

export default function DashboardLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<AppRouterCacheProvider>
			<ThemeProvider theme={theme}>
				<DashboardPageLayout children={children} />
			</ThemeProvider>
		</AppRouterCacheProvider>
	)
}
